### PR TITLE
#3 Handling circular type definitions

### PR DESCRIPTION
**Pull request by marekjagielski**

### CODE REVIEW

**Comment by marekjagielski** [comment]
@randyzwitch can you check if it is working with your example, please?

**Comment by randyzwitch** [comment]
It appears as if this change might have helped, but I now I get an error elsewhere:

```R
> mapdthrift <- t_load("~/mapd-core/mapd.thrift")
Error in value[[3L]](cond) : Type error for field table_type at line 189
```

If you want to test against the same file I'm using, you can find it here:
https://github.com/omnisci/mapd-core
https://github.com/omnisci/mapd-core/blob/master/mapd.thrift

**Comment by randyzwitch** [comment]
Actually, it looks like the error above is #4

**Comment by randyzwitch** [comment]
Yes, once I deleted all the enum definitions, this fix allowed the circular definitions.

**Comment by marekjagielski** [comment]
Ok,
Thanks @randyzwitch .Yes, enums are completely implemented in the wrong way. I need to rewrite it.

**Pull request merged**
